[package]
name = "golr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.3.0"
image = "0.23.14"
show-image = { version = "0.9.3", features = ["image"] }
